name: Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build CSS File
        run: npm run build

      - name: Create Test Build
        run: zip -r ./module.zip module.json LICENSE foundryvtt-devMode.mjs foundryvtt-devMode.css module/ templates/ lang/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: module-test-build
          path: ./module.zip
          retention-days: 5
